### ISSUE TITLE
Entries for /copyrightsans and /copyrightserif don't make sense

### ISSUE THREAD

**Issue by t3nsor** [adobe-type-tools/agl-aglfn#2]
copyrightsans;F8E9
copyrightserif;F6D9

These code points are in the private use area. Shouldn't they just be mapped to U+00a9 which is the actual copyright symbol?

**Comment by kenlunde** [comment]
The glyph named _copyright_ already maps to U+00A9. Please re-read the [AGL Specification](https://github.com/adobe-type-tools/agl-specification) to better understand the intent of the _glyphlist.txt_ data file.
